# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: audentes
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64

#package
package:
  individually: true # zipa cada lambda (api) de forma individual pra não ficar muito grande

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/signin.handler
    events:
      - httpApi:
          path: /
          method: get

  signup:
    handler: src/signup.handler
    events:
      - httpApi:
          path: /signup
          method: get
