# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: audentes
# "service" is the name of this project. This will also be added to your AWS resource names.
service: foodiary-api

plugins:
  - serverless-offline
# serverless local


provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    # Define environment variables here
    DATABASE_URL: ${env:DATABASE_URL} # Use the DATABASE_URL from .env file

#package
package:
  individually: true # zipa cada lambda (api) de forma individual pra não ficar muito grande

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
